version: '3.8'

volumes: 
  grafana-data: {}

networks:
  front-tier:
  back-tier:

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - back-tier
    ports:
      - "5432:5432"
  
  adminer:
    image: adminer
    restart: always
    networks:
      - back-tier
      - front-tier
    ports:
      - "8080:8080"

  grafana:
    image: grafana/grafana:latest
    user: "472"
    restart: always
    networks:
      - front-tier
      - back-tier
    ports:
      - "3000:3000"
    volumes:
      - ./config/grafana_datasources.yaml: /etc/grafana/provisioning/datasources/datasource.yaml:ro