apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: db.:5432
    database: test
    user: postgres
    password: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: disable